In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt

# Read Data

In [2]:
budget = pd.read_excel("C:\\Users\\Arief\\Documents\\Data Manipulation_L1\\Data-Manipulation-as-Beginner\\Data-Manipulation-as-Beginner\\data\\budget price.xlsx")
budget

c:\ProgramData\Anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

          Client                             Project      Code  Client budget
0  EcoStyle GMBH  Churn Prediction System Deployment  C001P001         6000.0
1  EcoStyle GMBH               Customer Segmentation  C001P002         6300.0
2  Stoplastic AD           Emails Sentiment Analysis  C002P001         5700.0

In [3]:
employee_rate = pd.read_excel("C:\\Users\\Arief\\Documents\\Data Manipulation_L1\\Data-Manipulation-as-Beginner\\Data-Manipulation-as-Beginner\\data\\employee.xlsx")
employee_rate

c:\ProgramData\Anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

         Name    Position Worker ID  Salary rate (gross)  Price rate
0  Anna Smith  Consultant     C_001                 17.4        37.4
1  John White  Consultant     C_002                 17.4        37.4
2  Maria Bach     Manager     M_001                 30.0        44.0
3   Max Klein      Intern     I_001                 10.8        26.8

In [4]:
project = pd.read_excel("C:\\Users\\Arief\\Documents\\Data Manipulation_L1\\Data-Manipulation-as-Beginner\\Data-Manipulation-as-Beginner\\data\\project_code.xlsx")
project

c:\ProgramData\Anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Client,Project,Code,Type
0,"Admin (proposals, contacts, billing)",-,I001,Internal
1,Internal meetings,-,I002,Internal
2,EcoStyle GMBH,Churn Prediction System Deployment,C001P001,Client
3,EcoStyle GMBH,Customer Segmentation,C001P002,Client
4,Stoplastic AD,Emails Sentiment Analysis,C002P001,Client

In [5]:
timesheet = pd.read_excel("C:\\Users\\Arief\\Documents\\Data Manipulation_L1\\Data-Manipulation-as-Beginner\\Data-Manipulation-as-Beginner\\data\\timesheets.xlsx")
timesheet

c:\ProgramData\Anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

           Date                Task      Code Worker ID     Start       End
0    02.11.2020  Preparing proposal      I001     C_001  08:30:00  12:00:00
1    02.11.2020    Internal meeting      I002     C_001  13:00:00  16:00:00
2    02.11.2020            Research  C001P001     C_001  16:00:00  18:00:00
3    03.11.2020            Research  C001P001     C_001  09:00:00  12:00:00
4    03.11.2020            Research  C001P001     C_001  13:00:00  16:00:00
..          ...                 ...       ...       ...       ...       ...
247  27.11.2020               Admin      I001     M_001  13:00:00  16:00:00
248  27.11.2020          Deployment  C002P001     M_001  16:00:00  18:00:00
249  30.11.2020    Internal meeting      I002     M_001  09:00:00  12:00:00
250  30.11.2020      Client meeting  C002P001     M_001  13:00:00  16:00:00
251  30.11.2020             Billing      I001     M_001  16:00:00  18:00:00

[252 rows x 6 columns]

# PREPROCESSING
Merge employee and project data

In [6]:
#join two tables. there are employee_rate and timesheet, to be a column whose name is join1
join1 = employee_rate.set_index('Worker ID').join(timesheet.set_index('Worker ID'), lsuffix = '_Left', rsuffix = '_Right', how = 'inner')
join1

,Name,Position,Salary rate (gross),Price rate,Date,Task,Code,Start,End
Worker ID,,,,,,,,,
C_001,Anna Smith,Consultant,17.4,37.4,02.11.2020,Preparing proposal,I001,08:30:00,12:00:00
C_001,Anna Smith,Consultant,17.4,37.4,02.11.2020,Internal meeting,I002,13:00:00,16:00:00
C_001,Anna Smith,Consultant,17.4,37.4,02.11.2020,Research,C001P001,16:00:00,18:00:00
C_001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Research,C001P001,09:00:00,12:00:00
C_001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Research,C001P001,13:00:00,16:00:00
...,...,...,...,...,...,...,...,...,...
M_001,Maria Bach,Manager,30.0,44.0,27.11.2020,Admin,I001,13:00:00,16:00:00
M_001,Maria Bach,Manager,30.0,44.0,27.11.2020,Deployment,C002P001,16:00:00,18:00:00
M_001,Maria Bach,Manager,30.0,44.0,30.11.2020,Internal meeting,I002,09:00:00,12:00:00
M_001,Maria Bach,Manager,30.0,44.0,30.11.2020,Client meeting,C002P001,13:00:00,16:00:00
M_001,Maria Bach,Manager,30.0,44.0,30.11.2020,Billing,I001,16:00:00,18:00:00

In [7]:
#join two table. There are join1 and , to be a column whose name join2
join2 = join1.set_index('Code').join(project.set_index('Code'), lsuffix = '_Left', rsuffix = '_Right', how = 'inner')
join2

,Name,Position,Salary rate (gross),Price rate,Date,Task,Start,End,Client,Project,Type
Code,,,,,,,,,,,
C001P001,Anna Smith,Consultant,17.4,37.4,02.11.2020,Research,16:00:00,18:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client
C001P001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Research,09:00:00,12:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client
C001P001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Research,13:00:00,16:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client
C001P001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Data pre-processing,16:00:00,18:30:00,EcoStyle GMBH,Churn Prediction System Deployment,Client
C001P001,Anna Smith,Consultant,17.4,37.4,04.11.2020,Data pre-processing,09:00:00,12:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client
...,...,...,...,...,...,...,...,...,...,...,...
I002,Maria Bach,Manager,30.0,44.0,10.11.2020,Internal meeting,09:00:00,12:00:00,Internal meetings,-,Internal
I002,Maria Bach,Manager,30.0,44.0,11.11.2020,Internal meeting,13:00:00,16:00:00,Internal meetings,-,Internal
I002,Maria Bach,Manager,30.0,44.0,19.11.2020,Internal meeting,09:00:00,12:00:00,Internal meetings,-,Internal
I002,Maria Bach,Manager,30.0,44.0,20.11.2020,Internal meeting,13:00:00,16:00:00,Internal meetings,-,Internal
I002,Maria Bach,Manager,30.0,44.0,30.11.2020,Internal meeting,09:00:00,12:00:00,Internal meetings,-,Internal

# MANIPULATION
1. Join date & Start time
2. Join date & end time
3. String to date & time
4. Count minutes

In [8]:
# Create a DataFrame from the previous data
mnp = pd.DataFrame(join2)

a. convert "Start" column to string data type
b. Joining Date and Start columns

In [9]:
dst = pd.DataFrame(mnp)
# Convert 'Start' column to string
dst['Start'] = dst['Start'].astype(str)
# Join Date and Start columns
dst['DateStartTime'] = dst['Date'] + 'T' + dst['Start']
dst

,Name,Position,Salary rate (gross),Price rate,Date,Task,Start,End,Client,Project,Type,DateStartTime
Code,,,,,,,,,,,,
C001P001,Anna Smith,Consultant,17.4,37.4,02.11.2020,Research,16:00:00,18:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,02.11.2020T16:00:00
C001P001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Research,09:00:00,12:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,03.11.2020T09:00:00
C001P001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Research,13:00:00,16:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,03.11.2020T13:00:00
C001P001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Data pre-processing,16:00:00,18:30:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,03.11.2020T16:00:00
C001P001,Anna Smith,Consultant,17.4,37.4,04.11.2020,Data pre-processing,09:00:00,12:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,04.11.2020T09:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
I002,Maria Bach,Manager,30.0,44.0,10.11.2020,Internal meeting,09:00:00,12:00:00,Internal meetings,-,Internal,10.11.2020T09:00:00
I002,Maria Bach,Manager,30.0,44.0,11.11.2020,Internal meeting,13:00:00,16:00:00,Internal meetings,-,Internal,11.11.2020T13:00:00
I002,Maria Bach,Manager,30.0,44.0,19.11.2020,Internal meeting,09:00:00,12:00:00,Internal meetings,-,Internal,19.11.2020T09:00:00
I002,Maria Bach,Manager,30.0,44.0,20.11.2020,Internal meeting,13:00:00,16:00:00,Internal meetings,-,Internal,20.11.2020T13:00:00
I002,Maria Bach,Manager,30.0,44.0,30.11.2020,Internal meeting,09:00:00,12:00:00,Internal meetings,-,Internal,30.11.2020T09:00:00

c. Convert column "End" to string data type
d. Joining date and End columns

In [10]:
det = pd.DataFrame(mnp)
#convert 'End' column to string
det['End'] = det['End'].astype(str)
# Join Date and End columns
det['DateEndTime'] = det['Date'] + 'T' + det['End']
det

,Name,Position,Salary rate (gross),Price rate,Date,Task,Start,End,Client,Project,Type,DateStartTime,DateEndTime
Code,,,,,,,,,,,,,
C001P001,Anna Smith,Consultant,17.4,37.4,02.11.2020,Research,16:00:00,18:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,02.11.2020T16:00:00,02.11.2020T18:00:00
C001P001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Research,09:00:00,12:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,03.11.2020T09:00:00,03.11.2020T12:00:00
C001P001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Research,13:00:00,16:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,03.11.2020T13:00:00,03.11.2020T16:00:00
C001P001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Data pre-processing,16:00:00,18:30:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,03.11.2020T16:00:00,03.11.2020T18:30:00
C001P001,Anna Smith,Consultant,17.4,37.4,04.11.2020,Data pre-processing,09:00:00,12:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,04.11.2020T09:00:00,04.11.2020T12:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
I002,Maria Bach,Manager,30.0,44.0,10.11.2020,Internal meeting,09:00:00,12:00:00,Internal meetings,-,Internal,10.11.2020T09:00:00,10.11.2020T12:00:00
I002,Maria Bach,Manager,30.0,44.0,11.11.2020,Internal meeting,13:00:00,16:00:00,Internal meetings,-,Internal,11.11.2020T13:00:00,11.11.2020T16:00:00
I002,Maria Bach,Manager,30.0,44.0,19.11.2020,Internal meeting,09:00:00,12:00:00,Internal meetings,-,Internal,19.11.2020T09:00:00,19.11.2020T12:00:00
I002,Maria Bach,Manager,30.0,44.0,20.11.2020,Internal meeting,13:00:00,16:00:00,Internal meetings,-,Internal,20.11.2020T13:00:00,20.11.2020T16:00:00
I002,Maria Bach,Manager,30.0,44.0,30.11.2020,Internal meeting,09:00:00,12:00:00,Internal meetings,-,Internal,30.11.2020T09:00:00,30.11.2020T12:00:00

e. convert data type from string to datetime

In [11]:
from datetime import datetime

# Create DataFrame
mnp = pd.DataFrame(det)

# Convert strings to datetime objects -> DateStartTime's column & DateEndTime's Column
mnp[['DateStartTime', 'DateEndTime']] = mnp[['DateStartTime', 'DateEndTime']].apply(pd.to_datetime)

#Show data types
data_types = mnp.dtypes
data_types

Name                           object
Position                       object
Salary rate (gross)           float64
Price rate                    float64
Date                           object
Task                           object
Start                          object
End                            object
Client                         object
Project                        object
Type                           object
DateStartTime          datetime64[ns]
DateEndTime            datetime64[ns]
dtype: object

f. Time granularity

In [12]:
# Calculate the difference in minutes
mnp['granularity'] = (mnp['DateEndTime'] - mnp['DateStartTime']).dt.total_seconds() / 60
mnp

,Name,Position,Salary rate (gross),Price rate,Date,Task,Start,End,Client,Project,Type,DateStartTime,DateEndTime,granularity
Code,,,,,,,,,,,,,,
C001P001,Anna Smith,Consultant,17.4,37.4,02.11.2020,Research,16:00:00,18:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,2020-02-11 16:00:00,2020-02-11 18:00:00,120.0
C001P001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Research,09:00:00,12:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,2020-03-11 09:00:00,2020-03-11 12:00:00,180.0
C001P001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Research,13:00:00,16:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,2020-03-11 13:00:00,2020-03-11 16:00:00,180.0
C001P001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Data pre-processing,16:00:00,18:30:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,2020-03-11 16:00:00,2020-03-11 18:30:00,150.0
C001P001,Anna Smith,Consultant,17.4,37.4,04.11.2020,Data pre-processing,09:00:00,12:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,2020-04-11 09:00:00,2020-04-11 12:00:00,180.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
I002,Maria Bach,Manager,30.0,44.0,10.11.2020,Internal meeting,09:00:00,12:00:00,Internal meetings,-,Internal,2020-10-11 09:00:00,2020-10-11 12:00:00,180.0
I002,Maria Bach,Manager,30.0,44.0,11.11.2020,Internal meeting,13:00:00,16:00:00,Internal meetings,-,Internal,2020-11-11 13:00:00,2020-11-11 16:00:00,180.0
I002,Maria Bach,Manager,30.0,44.0,19.11.2020,Internal meeting,09:00:00,12:00:00,Internal meetings,-,Internal,2020-11-19 09:00:00,2020-11-19 12:00:00,180.0
I002,Maria Bach,Manager,30.0,44.0,20.11.2020,Internal meeting,13:00:00,16:00:00,Internal meetings,-,Internal,2020-11-20 13:00:00,2020-11-20 16:00:00,180.0
I002,Maria Bach,Manager,30.0,44.0,30.11.2020,Internal meeting,09:00:00,12:00:00,Internal meetings,-,Internal,2020-11-30 09:00:00,2020-11-30 12:00:00,180.0

# Calculate real price &  salary expense for each project

Change the name

In [13]:
mnp = mnp.rename(columns={'Salary rate (gross)' : 'Salary_rate_gross', 'Price rate': 'Price_rate'})
print(mnp)

                Name    Position  Salary_rate_gross  Price_rate        Date  \
Code
C001P001  Anna Smith  Consultant               17.4        37.4  02.11.2020
C001P001  Anna Smith  Consultant               17.4        37.4  03.11.2020
C001P001  Anna Smith  Consultant               17.4        37.4  03.11.2020
C001P001  Anna Smith  Consultant               17.4        37.4  03.11.2020
C001P001  Anna Smith  Consultant               17.4        37.4  04.11.2020
...              ...         ...                ...         ...         ...
I002      Maria Bach     Manager               30.0        44.0  10.11.2020
I002      Maria Bach     Manager               30.0        44.0  11.11.2020
I002      Maria Bach     Manager               30.0        44.0  19.11.2020
I002      Maria Bach     Manager               30.0        44.0  20.11.2020
I002      Maria Bach     Manager               30.0        44.0  30.11.2020

                         Task     Start       End             Client  \
Code
C001P001             Research  16:00:00  18:00:00      EcoStyle GMBH
C001P001             Research  09:00:00  12:00:00      EcoStyle GMBH
C001P001             Research  13:00:00  16:00:00      EcoStyle GMBH
C001P001  Data pre-processing  16:00:00  18:30:00      EcoStyle GMBH
C001P001  Data pre-processing  09:00:00  12:00:00      EcoStyle GMBH
...                       ...       ...       ...                ...
I002         Internal meeting  09:00:00  12:00:00  Internal meetings
I002         Internal meeting  13:00:00  16:00:00  Internal meetings
I002         Internal meeting  09:00:00  12:00:00  Internal meetings
I002         Internal meeting  13:00:00  16:00:00  Internal meetings
I002         Internal meeting  09:00:00  12:00:00  Internal meetings

                                     Project      Type       DateStartTime  \
Code
C001P001  Churn Prediction System Deployment    Client 2020-02-11 16:00:00
C001P001  Churn Prediction System Deployment    Client 2020-03-11 09:00:00
C001P001  Churn Prediction System Deployment    Client 2020-03-11 13:00:00
C001P001  Churn Prediction System Deployment    Client 2020-03-11 16:00:00
C001P001  Churn Prediction System Deployment    Client 2020-04-11 09:00:00
...                                      ...       ...                 ...
I002                                       -  Internal 2020-10-11 09:00:00
I002                                       -  Internal 2020-11-11 13:00:00
I002                                       -  Internal 2020-11-19 09:00:00
I002                                       -  Internal 2020-11-20 13:00:00
I002                                       -  Internal 2020-11-30 09:00:00

                 DateEndTime  granularity
Code
C001P001 2020-02-11 18:00:00        120.0
C001P001 2020-03-11 12:00:00        180.0
C001P001 2020-03-11 16:00:00        180.0
C001P001 2020-03-11 18:30:00        150.0
C001P001 2020-04-11 12:00:00        180.0
...                      ...          ...
I002     2020-10-11 12:00:00        180.0
I002     2020-11-11 16:00:00        180.0
I002     2020-11-19 12:00:00        180.0
I002     2020-11-20 16:00:00        180.0
I002     2020-11-30 12:00:00        180.0

[252 rows x 14 columns]

In [18]:

mnp['Salary_rate_pertask'] = round(mnp['granularity'] * mnp['Salary_rate_gross'] / 60, 2)
mnp['Price_rate_pertask'] = round(mnp['granularity'] * mnp['Price_rate'] / 60, 2)
mnp

,Name,Position,Salary_rate_gross,Price_rate,Date,Task,Start,End,Client,Project,Type,DateStartTime,DateEndTime,granularity,Salary_rate_pertask,Price_rate_pertask
Code,,,,,,,,,,,,,,,,
C001P001,Anna Smith,Consultant,17.4,37.4,02.11.2020,Research,16:00:00,18:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,2020-02-11 16:00:00,2020-02-11 18:00:00,120.0,34.8,74.8
C001P001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Research,09:00:00,12:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,2020-03-11 09:00:00,2020-03-11 12:00:00,180.0,52.2,112.2
C001P001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Research,13:00:00,16:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,2020-03-11 13:00:00,2020-03-11 16:00:00,180.0,52.2,112.2
C001P001,Anna Smith,Consultant,17.4,37.4,03.11.2020,Data pre-processing,16:00:00,18:30:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,2020-03-11 16:00:00,2020-03-11 18:30:00,150.0,43.5,93.5
C001P001,Anna Smith,Consultant,17.4,37.4,04.11.2020,Data pre-processing,09:00:00,12:00:00,EcoStyle GMBH,Churn Prediction System Deployment,Client,2020-04-11 09:00:00,2020-04-11 12:00:00,180.0,52.2,112.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
I002,Maria Bach,Manager,30.0,44.0,10.11.2020,Internal meeting,09:00:00,12:00:00,Internal meetings,-,Internal,2020-10-11 09:00:00,2020-10-11 12:00:00,180.0,90.0,132.0
I002,Maria Bach,Manager,30.0,44.0,11.11.2020,Internal meeting,13:00:00,16:00:00,Internal meetings,-,Internal,2020-11-11 13:00:00,2020-11-11 16:00:00,180.0,90.0,132.0
I002,Maria Bach,Manager,30.0,44.0,19.11.2020,Internal meeting,09:00:00,12:00:00,Internal meetings,-,Internal,2020-11-19 09:00:00,2020-11-19 12:00:00,180.0,90.0,132.0
I002,Maria Bach,Manager,30.0,44.0,20.11.2020,Internal meeting,13:00:00,16:00:00,Internal meetings,-,Internal,2020-11-20 13:00:00,2020-11-20 16:00:00,180.0,90.0,132.0
I002,Maria Bach,Manager,30.0,44.0,30.11.2020,Internal meeting,09:00:00,12:00:00,Internal meetings,-,Internal,2020-11-30 09:00:00,2020-11-30 12:00:00,180.0,90.0,132.0